const words = [
  { word: "Key:", definition: "1- ilcfrssdwg" },
  { word: "Impecunious:", definition: "having little or no money." },
  { word: "Imperturbable:", definition: "unable to be upset or excited." },
  { word: "Impervious:", definition: "not affected or influenced by." },
  { word: "Impetuous:", definition: "acting quickly without thought." },
  { word: "Implacable:", definition: "unable to be placated or appeased." },
  { word: "Inchoate:", definition: "just begun; not fully formed." },
  { word: "Indefatigable:", definition: "persisting tirelessly." },
  { word: "Ineffable:", definition: "too great to be expressed in words." },
  { word: "Inimical:", definition: "hostile or unfriendly." },
  { word: "Insidious:", definition: "proceeding in a subtle but harmful way." },
  { word: "Insipid:", definition: "lacking flavor or interest." },
  { word: "Intrepid:", definition: "fearless and adventurous." },
  { word: "Inveterate:", definition: "having a long-established habit." },
  { word: "Jocular:", definition: "fond of joking; humorous." },
  { word: "Juxtapose:", definition: "to place side by side for contrast." },
  { word: "Laconic:", definition: "using few words." },
  { word: "Lament:", definition: "to express sorrow or regret." },
  { word: "Largesse:", definition: "generosity in giving." },
  { word: "Mendacious:", definition: "lying or untruthful." },
  { word: "Munificent:", definition: "very generous." },
  { word: "Nebulous:", definition: "vague or ill-defined." },
  { word: "Noxious:", definition: "harmful or poisonous." },
  { word: "Obdurate:", definition: "stubbornly refusing to change." },
  { word: "Obfuscate:", definition: "to confuse or make unclear." },
  { word: "Obsequious:", definition: "excessively obedient or attentive." },
  { word: "Officious:", definition: "meddlesome or overly eager to help." },
  { word: "Ostentatious:", definition: "showy or pretentious display." },
  { word: "Paradigm:", definition: "a typical example or pattern." },
  { word: "Pejorative:", definition: "expressing contempt or disapproval." },
  { word: "Penchant:", definition: "a strong liking or preference." },
  { word: "Perfunctory:", definition: "done without enthusiasm or care." },
  { word: "Phlegmatic:", definition: "calm and unemotional." },
  { word: "Placate:", definition: "to soothe or pacify." },
  { word: "Platitude:", definition: "a trite or obvious remark." },
  { word: "Plethora:", definition: "an excess or large amount." },
  { word: "Precocious:", definition: "advanced in development for one's age." },
  { word: "Proclivity:", definition: "a natural inclination or tendency." },
  { word: "Quixotic:", definition: "unrealistic and impractical." },
  { word: "Recalcitrant:", definition: "resisting authority or control." },
  { word: "Reprobate:", definition: "a morally unprincipled person." },
  { word: "Sagacious:", definition: "wise or shrewd." },
  { word: "Sanguine:", definition: "optimistic or positive." },
  { word: "Spurious:", definition: "not genuine or true." },
  { word: "Supercilious:", definition: "arrogant or condescending." },
  { word: "Surreptitious:", definition: "kept secret or hidden." },
  { word: "Taciturn:", definition: "reserved or uncommunicative." },
  { word: "Tantamount:", definition: "equivalent in effect or value." },
  { word: "Trenchant:", definition: "incisive and keen." },
  { word: "Ubiquitous:", definition: "present everywhere." },
  { word: "Vacillate:", definition: "to waver between choices." },
  { word: "Venerable:", definition: "worthy of respect." },
  { word: "Vicissitude:", definition: "a change or variation." },
  { word: "Vindicate:", definition: "to clear from blame or suspicion." },
  { word: "Vociferous:", definition: "loud and forceful." },
  { word: "Winsome:", definition: "attractive or charming." },
  { word: "Zephyr:", definition: "a gentle breeze." },
];

const randomIndex = Math.floor(Math.random() * words.length);
const todayWord = words[randomIndex];

document.getElementById("word").textContent = todayWord.word;
document.getElementById("definition").textContent = todayWord.definition;
